### ISSUE TITLE
[boost] Cannot statically link with CMake and Visual Studio

### ISSUE THREAD

**Issue by firewave** [conan-community/community#134]
### Description of Problem, Request, or Question

Using Visual Studio 2015 and CMake 3.13.2 (the only versions I currently have available). I am not able to link a program using the static libraries (`boost:shared=False`).

Using the default settings or `boost:magic_autolink=True`
```
LINK : fatal error LNK1104: cannot open file 'libboost_log-vc140-mt-x64-1_69.lib'
```

Using `boost:skip_lib_rename=True`
```
CMake Error at C:/Program Files/cmake/win/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.
```

I am detecting the boost library using
```
find_package(Boost 1.69 EXACT REQUIRED COMPONENTS filesystem program_options regex system log log_setup date_time)
```
and use `Boost_LIBRARIES` variable in `target_link_libraries`.

I haven't tried using the shared libraries yet as this requires some changes to my project. I will do this in the next few days.

It was working a few months back, but I am not sure if the project was using static or shared libraries at that point.

### Package Details
* Package Name/Version: **boost/1.69**
* Operating System: **Windows 10**
* Operation System Version: **Version 1809 (OS Build 17763.253)**
* Compiler+version: **MSVC 19.0.24215.1**
* Conan version: **conan 1.11.1**
* Python version: **python 3.6.4**

**Comment by firewave** [comment]
I think this is pretty much a duplicate of #83 which was closed without a proper conclusion.

**Comment by SSE4** [comment]
initial investigation shows the following.
boost has 3 library named schemes (`layout` parameter of b2):
- `system`, libraries are named like `libboost_log.lib` or `libboost_log.a`
- `versioned`, libraries are named like `libboost_log-vc140-mt-x64-1_69.lib` or `libboost_log-gcc-mt-x64-1_69.a`
- `tagged`, libraries are named like `libboost_log-mt-x64.lib` or `libboost_log-mt.a`
or from `b2 --help`:
```
#   --layout=<layout>       Determines whether to choose library names
#                           and header locations such that multiple
#                           versions of Boost or multiple compilers can
#                           be used on the same system.
#
#                               versioned - Names of boost binaries
#                               include the Boost version number, name and
#                               version of the compiler and encoded build
#                               properties.  Boost headers are installed in a
#                               subdirectory of <HDRDIR> whose name contains
#                               the Boost version number.
#
#                               tagged -- Names of boost binaries include the
#                               encoded build properties such as variant and
#                               threading, but do not including compiler name
#                               and version, or Boost version. This option is
#                               useful if you build several variants of Boost,
#                               using the same compiler.
#
#                               system - Binaries names do not include the
#                               Boost version number or the name and version
#                               number of the compiler.  Boost headers are
#                               installed directly into <HDRDIR>.  This option
#                               is intended for system integrators who are
#                               building distribution packages.
#
#                           The default value is 'versioned' on Windows, and
#                           'system' on Unix.
```
on Visual Studio, boost has so-called `auto-linking` feature, where it uses [#pragma comment(lib xxx)](https://docs.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp?view=vs-2017) feature, which allows consumer to avoid dealing with linker options, just include boost headers and get all boost libraries linked automatically. it's controlled by `BOOST_ALL_NO_LIB` macro (or by specific macro definitions per library).
auto-linking is mainly controlled by the `[auto_link.hpp](https://github.com/boostorg/config/blob/develop/include/boost/config/auto_link.hpp)` header from the boost config library.
the header defines some macro to control auto-linking properties:
```
BOOST_AUTO_LINK_NOMANGLE: Specifies that we should link to BOOST_LIB_NAME.lib,
                          rather than a mangled-name version.
BOOST_AUTO_LINK_TAGGED:   Specifies that we link to libraries built with the --layout=tagged option.
                          This is essentially the same as the default name-mangled version, but without
                          the compiler name and version, or the Boost version.  Just the build options.
BOOST_AUTO_LINK_SYSTEM:   Specifies that we link to libraries built with the --layout=system option.
                          This is essentially the same as the non-name-mangled version, but with
                          the prefix to differentiate static and dll builds
```
probably, defining either `BOOST_AUTO_LINK_NOMANGLE` or `BOOST_AUTO_LINK_SYSTEM` should cure the issue.
fix is pretty complex and includes 3 steps, as I can see right now:
1. for simplicity, just always use `--layout=system`, as we rename libraries to the system layout anyway
2. remove `skip_lib_rename` option and remove `renames_to_make_cmake_find_package_happy` method, as useless (layout should care about the correct naming)
3. `package_info` should define `BOOST_AUTO_LINK_NOMANGLE` or `BOOST_AUTO_LINK_SYSTEM`, if `boost:magic_autolink=True`
4. (optional) add `layout` option with values: `tagged`, `versioned` and `system` (default)

**Comment by SSE4** [comment]
@firewave could you try to define `BOOST_AUTO_LINK_NOMANGLE ` or `BOOST_AUTO_LINK_SYSTEM` and see if it helps? I am running local tests as well.

**Comment by SSE4** [comment]
@lasote do you remember why did we add `skip_lib_rename` and rename function? may be link to some issues?
git blame found , but it doesn't say much https://github.com/conan-community/conan-boost/commit/28a273472b4763a38bd8b8fbd44a63e85453254d

**Comment by firewave** [comment]
Thanks for the analysis - will do some testing in the next few days.

**Comment by SSE4** [comment]
@firewave I've pushed changes to the `layout/1.69` branch, it would be nice if you could give a try.

**Comment by firewave** [comment]
My analysis...

CMake fails to find the static libraries by default now:

```
...
-- Current conanbuildinfo.cmake directory: C:/clion/broker/.conan-vs
-- Conan: Using cmake targets configuration
...
-- Library libboost_filesystem found C:/.conan/x_b9y902/1/lib/libboost_filesystem.lib
...
CMake Error at C:/Program Files/cmake/win/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: C:/.conan/x_b9y902/1/include

  Could not find the following Boost libraries:

          boost_filesystem
          boost_program_options
          boost_regex
          boost_system
          boost_log
          boost_log_setup
          boost_date_time
```

I had to specify `Boost_USE_STATIC_LIBS` for the libraries to be found.

It still failed with 
```
LINK : fatal error LNK1104: cannot open file 'libboost_log-vc140-mt-x64-1_69.lib'
```
using the default settings though.

I tried `add_definitions(${Boost_LIB_DIAGNOSTIC_DEFINITIONS})` as suggested on https://cmake.org/cmake/help/v3.8/module/FindBoost.html but it seems you have to specify/invoke `Boost::diagnostic_definitions` somehow, but I how no idea how (I just added it to my `target_link_libraries`).

Using that I get the following output
```
Linking to lib file: libboost_log-vc140-mt-x64-1_69.lib
Linking to lib file: libboost_filesystem-vc140-mt-x64-1_69.lib
Linking to lib file: libboost_date_time-vc140-mt-x64-1_69.lib
Linking to lib file: libboost_thread-vc140-mt-x64-1_69.lib
Linking to lib file: libboost_regex-vc140-mt-x64-1_69.lib
Linking to lib file: libboost_program_options-vc140-mt-x64-1_69.lib
```

So it doesn't look for the system libraries since `boost:magic_autolink=False` is the default and the proper define is not specified. 

But changing that didn't help either since you obviously you need to specify `BOOST_AUTO_LINK_SYSTEM` and similar not while building the library (some are already offered via FindBoost), but in the project you are including boost in. Doing that will finally get it to link.

I have not done any testing using the shared libraries.

**Comment by SSE4** [comment]
@firewave so, `BOOST_AUTO_LINK_SYSTEM` is not defined for you?
it's weird since it should be here https://github.com/conan-community/conan-boost/commit/4c476fcbebf00a12618e2b62f84ec2424efc96d1#diff-2b1d42f71f22b7ea0412d7602dec166fR693

**Comment by firewave** [comment]
Yeah - I saw it in `conanbuildinfo.cmake`. But since I am using it in CMake via FindBoost and none of the conan variable I am not getting any of the additional defines conan provides. And mixing `find_package` defined ones with conan ones feels a bit messy to me (although it might be the proper way to do it).

**Comment by SSE4** [comment]
that's probably the only correct way to lnk static boost with system layout - define `Boost_USE_STATIC_LIBS ` in CMake and define `BOOST_AUTO_LINK_SYSTEM` in preprocessor as well

**Comment by theodelrieu** [comment]
I've seen the same problem recently (on a forked recipe of Boost). What I've done is:

* use `--layout=system`
* rename libs from `libboost_*` to `boost_*`
* compile with `BOOST_ALL_NO_LIB`

**Comment by SSE4** [comment]
@theodelrieu I believe your steps are correct, except that rename isn't needed, just need to define `Boost_USE_STATIC_LIBS` in CMake (static and shared boost libraries differ by lib prefix)

**Comment by theodelrieu** [comment]
I had this define as well.

`find_library` called in `FindBoost.cmake` with `boost_context` as its first argument.

According to CMake documentation, the standard prefix `lib` is prepended automatically on Unix like systems, but there is no standard prefix on Windows.

Therefore I still think the rename is mandatory.

**Comment by SSE4** [comment]
that's weird, as for me it worked. also, I see the following in their code: https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake#L1439
so, it should append lib prefix for Windows, isn't it?

**Comment by theodelrieu** [comment]
Sorry, I misread that it was a CMake option, I was talking about a compiler definition...

Still, if I package a library depending on Boost, I'd like to not have to patch the library's CMake files to add that line.

**Comment by SSE4** [comment]
@theodelrieu but if library uses system boost, or boost compiled manually (without conan), it would be the same issue, isn't it? how does it work in that case?

**Comment by theodelrieu** [comment]
To be honest, I have no idea 😄

**Comment by firewave** [comment]
As it fixes the issues for me I am wondering when the `layout/1.69` branch will be merged into master?

**Comment by SSE4** [comment]
@firewave I am merging it

**Comment by SSE4** [comment]
@firewave changes were merged, is it okay to close it now?

**Comment by firewave** [comment]
Thanks.

Yes, go ahead and close it.

**Comment by SSE4** [comment]
confirmed as fixed, closing

**Comment by martinitus** [comment]
I had a similar issue linking on windows with cmake and conan, thanks for the tips!

```
find_package(Boost REQUIRED COMPONENTS beasts)
target_link_libraries(srv PRIVATE ${Boost_LIBRARIES})
if(MSVC)
    target_compile_definitions(srv PRIVATE BOOST_AUTO_LINK_SYSTEM) # i was lacking this
endif()
```
❤️
