### ISSUE TITLE
[Boost] error: No best alternative for libs/context/build/asm_sources

### ISSUE THREAD

**Issue by acgetchell** [conan-community/community#135]
### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.69.0**
* Operating System: **macOS**
* Operation System Version: **10.13**
* Compiler+version: **gcc-8.2**
* Conan version: **conan 1.11.2**

### Steps to reproduce (Include if Applicable)

Use conan to install boost on macOS using gcc.

### Build logs (Include if Available)

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/480255840#L2086

**Comment by SSE4** [comment]
b2 command line:
```
b2 target-os=darwin architecture=x86 address-model=64 binary-format=mach-o abi=sysv --layout=system link=static variant=release --without-python define=_GLIBCXX_USE_CXX11_ABI=1 cxxflags="-fPIC" -j2 --abbreviate-paths -d2 --debug-configuration --build-dir="/Users/travis/.conan/data/boost/1.69.0/conan/stable/build/e374b09b32f2a1300980d66c6801b17751eb1b80"
```
so, it sets: 
```
<abi>sysv
<address-model>64
<architecture>x86
<binary-format>mach-o
<toolset>gcc
```
seems to be the only missing property is `<threading>` (obviously, boost::context usage makes sense only in mutli-threaded environment).
currently, conan only sets it for GCC Windows for some reason:
I believe, it should be safe to set it always.

**Comment by SSE4** [comment]
@acgetchell I've pushed changes to always use `threading=multi`: https://github.com/conan-community/conan-boost/commit/1b49ba64123ed03fbf937ec38e9e6c3a217ee97b
please give an another try and lemme know

**Comment by acgetchell** [comment]
Still occurs.

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/482717218#L2122

**Comment by SSE4** [comment]
@acgetchell seems like we had a bug when `toolset` argument wasn't passed on command line. I've fixed it: https://github.com/conan-community/conan-boost/commit/08903e8851c33b5d473c534eb69c77fd4616fa43
could you possibly give an another try and lemme know

**Comment by acgetchell** [comment]
If my Travis-CI job is building Boost with your updated package:

```
boost/1.69.0@conan/stable: Building your package in /Users/travis/.conan/data/boost/1.69.0/conan/stable/build/e374b09b32f2a1300980d66c6801b17751eb1b80
boost/1.69.0@conan/stable: Configuring sources in /Users/travis/.conan/data/boost/1.69.0/conan/stable/source
boost/1.69.0@conan/stable: Copying sources to build folder
boost/1.69.0@conan/stable: Generator txt created conanbuildinfo.txt
boost/1.69.0@conan/stable: Calling build()
boost/1.69.0@conan/stable: Using gcc 8
boost/1.69.0@conan/stable: ./bootstrap.sh -with-toolset=gcc
-n Bootstrapping the build engine with toolset gcc... 
engine/bin.macosxx86_64/b2
Bootstrapping is done. To build and install, run:
    ./b2 install --prefix=<DIR>
```

Then I am still getting the error:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/486240799#L2163

But the line:

```
boost/1.69.0@conan/stable: Building your package in /Users/travis/.conan/data/boost/1.69.0/conan/stable/build/e374b09b32f2a1300980d66c6801b17751eb1b80
```

Matches the build prior to your fix, so I'm not sure. Is there something else I should be doing to ensure I'm getting your version?

**Comment by SSE4** [comment]
at least, now it passes toolset to he b2 command line:
```
boost/1.69.0@conan/stable: WARN: /Users/travis/.conan/data/boost/1.69.0/conan/stable/source/boost_1_69_0/tools/build/b2 target-os=darwin architecture=x86 address-model=64 binary-format=mach-o abi=sysv --layout=system threading=multi link=static variant=release --without-python toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 cxxflags="-fPIC" -j2 --abbreviate-paths -d2 --debug-configuration --build-dir="/Users/travis/.conan/data/boost/1.69.0/conan/stable/build/e374b09b32f2a1300980d66c6801b17751eb1b80"
```
(there is *toolset=gcc*)
so, it seems to be newer version
I need to investigate it further

**Comment by acgetchell** [comment]
Also does not build on Travis-CI osx_image: xcode10.2 (i.e. macOS Mojave).

**Comment by SSE4** [comment]
@acgetchell I've pushed the fix to use "darwin" toolchain instead of "gcc" on OSX: https://github.com/conan-community/conan-boost/commit/6e59a0b813b1babea572b24fa3c14e20332dcf02
it worked for me locally (with GCC installed from brew)
please give an another try and lemme know

**Comment by acgetchell** [comment]
Okay, that particular error is gone.

Boost still doesn't build.

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/512902318#L2638

I'll open another ticket.

**Comment by acgetchell** [comment]
Thank you @SSE4 for your efforts!
